# Main configuration file for HaloPlex analysis
settings:
  target_generator_handler: ratatosk.ext.scilife.sample.target_generator
  
misc:
  ResyncMates:
    parent_task: ratatosk.lib.utils.cutadapt.CutadaptJobTask

bwa:
  aln:
    parent_task: ratatosk.lib.utils.misc.ResyncMatesJobTask

samtools:
  SamToBam:
    parent_task: ratatosk.pipeline.haloplex.HaloBwaSampe

picard:
  SortSam:
    parent_task: ratatosk.lib.tools.samtools.SamToBam
  MergeSamFiles:
    parent_task: ratatosk.lib.tools.picard.SortSam
    target_generator_handler: ratatosk.ext.scilife.sample.collect_sample_runs
  DuplicationMetrics:
    parent_task: ratatosk.lib.tools.picard.MergeSamFiles
  AlignmentMetrics:
    parent_task: ratatosk.lib.tools.picard.MergeSamFiles
  InsertMetrics:
    parent_task: ratatosk.lib.tools.picard.MergeSamFiles
  HsMetrics:
    parent_task: ratatosk.lib.tools.picard.MergeSamFiles

gatk:
  # These are all subclassed for Halo, see dependencies below
  # RealignerTargetCreator:
  #   parent_task: ratatosk.lib.tools.picard.MergeSamFiles
  # IndelRealigner:
  #   parent_task: ratatosk.lib.tools.gatk.RealignerTargetCreator
  # BaseRecalibrator:
  #   parent_task: ratatosk.lib.tools.gatk.IndelRealigner
  PrintReads:
    parent_task: ratatosk.lib.tools.gatk.BaseRecalibrator
  ClipReads:
    parent_task: ratatosk.lib.tools.gatk.PrintReads
  UnifiedGenotyper:
    parent_task: ratatosk.lib.tools.gatk.ClipReads
  VariantFiltration:
    parent_task: ratatosk.lib.tools.gatk.UnifiedGenotyper
  VariantEval:
    parent_task: ratatosk.lib.tools.gatk.VariantFiltration

  # Addon tasks needed for HaloPlex
  RawUnifiedGenotyper:
    parent_task: ratatosk.lib.tools.picard.MergeSamFiles
  RawRealignerTargetCreator:
    parent_task: ratatosk.lib.tools.picard.MergeSamFiles
  RawIndelRealigner:
    parent_task: ratatosk.lib.tools.picard.MergeSamFiles
  # Finally, make BaseRecalibrator depend on RawIndelRealigner
  BaseRecalibrator:
    parent_task: ratatosk.pipeline.haloplex.RawIndelRealigner

htslib:
  VcfMerge:
    target_generator_handler: ratatosk.ext.scilife.sample.collect_vcf_files

    # This is inconsistent - should be handled by label. Has to do with how sample.collect_vcf_files is defined
    source_suffix: .trimmed.sync.sort.merge.realign.recal.clip.filtered.vcf.gz

tabix:
  Bgzip:
    parent_task: ratatosk.lib.tools.gatk.VariantFiltration
