# Main configuration file for HaloPlex analysis
settings:
  target_generator_handler: ratatosk.ext.scilife.sample.target_generator
  
misc:
  ResyncMates:
    parent_task: 
      - ratatosk.lib.utils.cutadapt.CutadaptJobTask
      - ratatosk.lib.utils.cutadapt.CutadaptJobTask

bwa:
  Aln:
    parent_task: ratatosk.lib.utils.misc.ResyncMatesJobTask
  Sampe:
    label: .trimmed.sync
    add_label:
      - _R1_001.trimmed.sync
      - _R2_001.trimmed.sync

samtools:
  SamToBam:
    parent_task: ratatosk.lib.align.bwa.Sampe

picard:
  SortSam:
    parent_task: ratatosk.lib.tools.samtools.SamToBam
  MergeSamFiles:
    parent_task: ratatosk.lib.tools.picard.SortSam
    target_generator_handler: ratatosk.ext.scilife.sample.collect_sample_runs
  DuplicationMetrics:
    parent_task: ratatosk.lib.tools.picard.MergeSamFiles
  AlignmentMetrics:
    parent_task: ratatosk.lib.tools.picard.MergeSamFiles
  InsertMetrics:
    parent_task: ratatosk.lib.tools.picard.MergeSamFiles
  HsMetrics:
    parent_task: ratatosk.lib.tools.picard.MergeSamFiles

gatk:
  # These are all subclassed for Halo, see dependencies below
  RealignerTargetCreator:
    parent_task: ratatosk.lib.tools.picard.MergeSamFiles
  IndelRealigner:
    parent_task:
    - ratatosk.lib.tools.picard.MergeSamFiles
    - ratatosk.lib.tools.gatk.RealignerTargetCreator
    - ratatosk.lib.tools.gatk.RawUnifiedGenotyper
  BaseRecalibrator:
    parent_task: ratatosk.lib.tools.gatk.IndelRealigner
  PrintReads:
    diff_label:
      - -phased
      - 
    parent_task:
      - ratatosk.lib.tools.picard.MergeSamFiles
      - ratatosk.lib.tools.gatk.BaseRecalibrator
  ClipReads:
    parent_task: ratatosk.lib.tools.gatk.PrintReads
  UnifiedGenotyper:
    parent_task: ratatosk.lib.tools.gatk.ClipReads
  VariantHaloFiltration:
    parent_task: ratatosk.lib.tools.gatk.UnifiedGenotyper
  VariantEval:
    parent_task: ratatosk.pipeline.haloplex.VariantHaloFiltration

  # Addon tasks needed for HaloPlex
  RawUnifiedGenotyper:
    parent_task: ratatosk.lib.tools.picard.MergeSamFiles
  RawRealignerTargetCreator:
    parent_task: ratatosk.lib.tools.picard.MergeSamFiles
  RawIndelRealigner:
    parent_task: ratatosk.lib.tools.picard.MergeSamFiles
  # Finally, make BaseRecalibrator depend on RawIndelRealigner
  BaseRecalibrator:
    #parent_task: ratatosk.pipeline.haloplex.RawIndelRealigner
    parent_task: ratatosk.pipeline.haloplex.IndelRealigner

htslib:
  VcfMerge:
    target_generator_handler: ratatosk.ext.scilife.sample.collect_vcf_files

    # This is inconsistent - should be handled by label. Has to do with how sample.collect_vcf_files is defined
    source_suffix: .trimmed.sync.sort.merge.realign.recal.clip.filtered.vcf.gz

tabix:
  Bgzip:
    parent_task: ratatosk.lib.tools.gatk.VariantFiltration

fastqc:
  parent_task: ratatosk.lib.utils.cutadapt.InputFastqFile
