settings:
  target_generator_handler: ratatosk.ext.scilife.sample.target_generator

picard:
  SortSam:
    parent_task: ratatosk.lib.align.bwa.Bampe
  MergeSamFiles:
    parent_task: ratatosk.lib.tools.picard.SortSam
    target_generator_handler: ratatosk.ext.scilife.sample.collect_sample_runs
  InputBamFile:
    parent_task: ratatosk.lib.align.bwa.Bampe
  HsMetrics:
    parent_task: ratatosk.lib.tools.picard.DuplicationMetrics
  DuplicationMetrics:
    parent_task: ratatosk.lib.tools.picard.MergeSamFiles
  AlignmentMetrics:
    parent_task: ratatosk.lib.tools.picard.DuplicationMetrics
  InsertMetrics:
    parent_task: ratatosk.lib.tools.picard.DuplicationMetrics

gatk:
  RealignerTargetCreator:
    parent_task: ratatosk.lib.tools.picard.DuplicationMetrics
  IndelRealigner:
    parent_task: ratatosk.lib.tools.picard.DuplicationMetrics
  BaseRecalibrator:
    options: 
      - --covariate CycleCovariate
      - --covariate ContextCovariate
    parent_task: ratatosk.lib.tools.gatk.IndelRealigner
  PrintReads:
    parent_task: ratatosk.lib.tools.gatk.BaseRecalibrator
  UnifiedGenotyper:
    parent_task: ratatosk.lib.tools.gatk.PrintReads
  SplitUnifiedGenotyper:
    parent_task: ratatosk.lib.tools.gatk.PrintReads
  SelectSnpVariants:
    parent_task: ratatosk.lib.tools.gatk.CombineVariants
  SelectIndelVariants:
    parent_task: ratatosk.lib.tools.gatk.CombineVariants
  VariantSnpRecalibrator:
    parent_task: ratatosk.lib.tools.gatk.SelectSnpVariants
  VariantIndelRecalibrator:
    parent_task: ratatosk.lib.tools.gatk.SelectIndelVariants
  VariantFiltration:
    parent_task: ratatosk.lib.tools.gatk.UnifiedGenotyper
  VariantEval:
    parent_task: ratatosk.lib.tools.gatk.VariantFiltration


fastqc:
  parent_task: ratatosk.lib.align.bwa.InputFastqFile
